/**
 * パフォーマンス最適化関連の定数
 * 
 * パーティクル、レンダリング、メモリ管理の設定値
 */

// パーティクル物理設定
export const PARTICLE_PHYSICS = {
  GRAVITY: 0.2,
  MAX_Y: 500,
  LIFE_DURATION: 60, // frames
  SCALE_BASE: 0.5,
  SCALE_MULTIPLIER: 1.5,
  OPACITY_MULTIPLIER: 0.9,
  PARTICLES_PER_CELL: 3,
} as const;

// パーティクルシステム設定
export const PARTICLE_CONFIG = {
  GRAVITY: 0.2,
  MAX_Y: 500,
  LIFE_MAX: 60,
  SCALE_BASE: 1.0,
  OPACITY_MULTIPLIER: 0.8,
  COUNT_PER_LINE: 15,
  POOL_SIZE: 100,
  MAX_PARTICLES: 200,
} as const;

// レンダリング最適化
export const PERFORMANCE = {
  RENDER_BATCH_SIZE: 20,
  CLEANUP_INTERVAL: 10000, // 10秒
} as const;

// 個別エクスポート（後方互換性）
export const PARTICLE_GRAVITY = PARTICLE_PHYSICS.GRAVITY;
export const PARTICLE_MAX_Y = PARTICLE_PHYSICS.MAX_Y;
export const PARTICLE_LIFE_DURATION = PARTICLE_PHYSICS.LIFE_DURATION;
export const PARTICLE_SCALE_BASE = PARTICLE_PHYSICS.SCALE_BASE;
export const PARTICLE_SCALE_MULTIPLIER = PARTICLE_PHYSICS.SCALE_MULTIPLIER;
export const PARTICLE_OPACITY_MULTIPLIER = PARTICLE_PHYSICS.OPACITY_MULTIPLIER;
export const PARTICLES_PER_CELL = PARTICLE_PHYSICS.PARTICLES_PER_CELL;